insert
	EEIUser.ST_LightingStudy_AirbagNA
	(	Component
	,	Service
	,	[Forecast Date]
	,	[VP: Mnemonic Vehicle/Plant]
	,	[VP: Mnemonic Vehicle]
	,	[VP: Mnemonic Platform]
	,	[VP: Region]
	,	[VP: Country]
	,	[VP: City]
	,	[VP: Market]
	,	[VP: Production Plant]
	,	[VP: Plant State/Province]
	,	[VP: Vehicle Plant Latitude]
	,	[VP: Vehicle Plant Longitude]
	,	[VP: Source Plant Region]
	,	[VP: Source Plant Country]
	,	[VP: Source Plant]
	,	[VP: Strategic Group]
	,	[VP: Design Parent]
	,	[VP: Sales Group]
	,	[VP: Sales Parent]
	,	[VP: Manufacturer Group]
	,	[VP: Manufacturer Parent]
	,	[VP: Production Brand]
	,	[VP: Production Nameplate]
	,	[VP: Platform]
	,	[VP: Program]
	,	[VP: SOP]
	,	[VP: EOP]
	,	[VP: Vehicle]
	,	[Global Nameplate - Airbag comp]
	,	[VP: Global Sales Segment]
	,	[VP: Global Sales Sub-Segment]
	,	[VP: Global Sales Price Class]
	,	[VP: Global Production Segment]
	,	[VP: Global Production Price Class]
	,	[VP: Regional Sales Segment]
	,	[VP: Regional Sales Price Class]
	,	[VP: Production Type]
	,	[VP: Assembly Type]
	,	[VP: Car/Truck]
	,	[VP: GVW Rating]
	,	[VP: GVW Class]
	,	[VP: Short Term Risk]
	,	[VP: Long Term Risk]
	,	[VP: Architecture]
	,	[VP: Engineering Group]
	,	[VP: Primary Design Center]
	,	[VP: Primary Design Country]
	,	[VP: Primary Design Region]
	,	[VP: Secondary Design Center]
	,	[VP: Secondary Design Country]
	,	[VP: Secondary Design Region]
	,	[Airbag Position]
	,	[Airbag Module Supplier Group]
	,	[Airbag Module Supplier]
	,	[Airbag Module Supplier Country]
	,	[Airbag Module Supplier Region]
	,	[Airbag Module Supplier Plant]
	,	[Airbag Module Units]
	,	[Vehicle Units]
	,	[Component Volume 2016]
	,	[Component Volume 2017]
	,	[Component Volume 2018]
	,	[Component Volume 2019]
	,	[Component Volume 2020]
	,	[Component Volume 2021]
	,	[Component Volume 2022]
	,	[Component Volume 2023]
	,	[Vehicle Volume 2016]
	,	[Vehicle Volume 2017]
	,	[Vehicle Volume 2018]
	,	[Vehicle Volume 2019]
	,	[Vehicle Volume 2020]
	,	[Vehicle Volume 2021]
	,	[Vehicle Volume 2022]
	,	[Vehicle Volume 2023]
	)
	select
		Component
	,	Service
	,	replace([Forecast Date], '/', '/01/') 
	,	[VP: Mnemonic Vehicle/Plant]
	,	[VP: Mnemonic Vehicle]
	,	[VP: Mnemonic Platform]
	,	[VP: Region]
	,	[VP: Country]
	,	[VP: City]
	,	[VP: Market]
	,	[VP: Production Plant]
	,	[VP: Plant State/Province]
	,	[VP: Vehicle Plant Latitude]
	,	[VP: Vehicle Plant Longitude]
	,	[VP: Source Plant Region]
	,	[VP: Source Plant Country]
	,	[VP: Source Plant]
	,	[VP: Strategic Group]
	,	[VP: Design Parent]
	,	[VP: Sales Group]
	,	[VP: Sales Parent]
	,	[VP: Manufacturer Group]
	,	[VP: Manufacturer Parent]
	,	[VP: Production Brand]
	,	[VP: Production Nameplate]
	,	[VP: Platform]
	,	[VP: Program]
	,	[VP: SOP]
	,	[VP: EOP]
	,	[VP: Vehicle]
	,	[Global Nameplate - Airbag comp]
	,	[VP: Global Sales Segment]
	,	[VP: Global Sales Sub-Segment]
	,	[VP: Global Sales Price Class]
	,	[VP: Global Production Segment]
	,	[VP: Global Production Price Class]
	,	[VP: Regional Sales Segment]
	,	[VP: Regional Sales Price Class]
	,	[VP: Production Type]
	,	[VP: Assembly Type]
	,	[VP: Car/Truck]
	,	[VP: GVW Rating]
	,	[VP: GVW Class]
	,	nullif([VP: Short Term Risk], '')
	,	nullif([VP: Long Term Risk], '')
	,	[VP: Architecture]
	,	[VP: Engineering Group]
	,	[VP: Primary Design Center]
	,	[VP: Primary Design Country]
	,	[VP: Primary Design Region]
	,	[VP: Secondary Design Center]
	,	[VP: Secondary Design Country]
	,	[VP: Secondary Design Region]
	,	[Airbag Position]
	,	[Airbag Module Supplier Group]
	,	[Airbag Module Supplier]
	,	[Airbag Module Supplier Country]
	,	[Airbag Module Supplier Region]
	,	[Airbag Module Supplier Plant]
	,	[Airbag Module Units]
	,	[Vehicle Units]
	,	[Component Volume 2016]
	,	[Component Volume 2017]
	,	[Component Volume 2018]
	,	[Component Volume 2019]
	,	[Component Volume 2020]
	,	[Component Volume 2021]
	,	[Component Volume 2022]
	,	[Component Volume 2023]
	,	[Vehicle Volume 2016]
	,	[Vehicle Volume 2017]
	,	[Vehicle Volume 2018]
	,	[Vehicle Volume 2019]
	,	[Vehicle Volume 2020]
	,	[Vehicle Volume 2021]
	,	[Vehicle Volume 2022]
	,	[Vehicle Volume 2023]
	from
		tempdb.dbo.ST_LightingStudy_Raw ls