drop table TempDB.dbo.ST_LightingStudy_Raw
go

create table TempDB.dbo.ST_LightingStudy_Raw
(
[Component]                                   varchar(max),
[Service]                                     varchar(max),
[Forecast Date]                               varchar(max),
[VP: Mnemonic Vehicle/Plant]                  varchar(max),
[VP: Mnemonic Vehicle]                        varchar(max),
[VP: Mnemonic Platform]                       varchar(max),
[VP: Region]                                  varchar(max),
[VP: Country]                                 varchar(max),
[VP: City]                                    varchar(max),
[VP: Market]                                  varchar(max),
[VP: Production Plant]                        varchar(max),
[VP: Plant State/Province]                    varchar(max),
[VP: Vehicle Plant Latitude]                  varchar(max),
[VP: Vehicle Plant Longitude]                 varchar(max),
[VP: Source Plant Region]                     varchar(max),
[VP: Source Plant Country]                    varchar(max),
[VP: Source Plant]                            varchar(max),
[VP: Strategic Group]                         varchar(max),
[VP: Design Parent]                           varchar(max),
[VP: Sales Group]                             varchar(max),
[VP: Sales Parent]                            varchar(max),
[VP: Manufacturer Group]                      varchar(max),
[VP: Manufacturer Parent]                     varchar(max),
[VP: Production Brand]                        varchar(max),
[VP: Production Nameplate]                    varchar(max),
[VP: Platform]                                varchar(max),
[VP: Program]                                 varchar(max),
[VP: SOP]                                     varchar(max),
[VP: EOP]                                     varchar(max),
[VP: Vehicle]                                 varchar(max),
[Global Nameplate - Airbag comp]              varchar(max),
[VP: Global Sales Segment]                    varchar(max),
[VP: Global Sales Sub-Segment]                varchar(max),
[VP: Global Sales Price Class]                varchar(max),
[VP: Global Production Segment]               varchar(max),
[VP: Global Production Price Class]           varchar(max),
[VP: Regional Sales Segment]                  varchar(max),
[VP: Regional Sales Price Class]              varchar(max),
[VP: Production Type]                         varchar(max),
[VP: Assembly Type]                           varchar(max),
[VP: Car/Truck]                               varchar(max),
[VP: GVW Rating]                              varchar(max),
[VP: GVW Class]                               varchar(max),
[VP: Short Term Risk]                         varchar(max),
[VP: Long Term Risk]                          varchar(max),
[VP: Architecture]                            varchar(max),
[VP: Engineering Group]                       varchar(max),
[VP: Primary Design Center]                   varchar(max),
[VP: Primary Design Country]                  varchar(max),
[VP: Primary Design Region]                   varchar(max),
[VP: Secondary Design Center]                 varchar(max),
[VP: Secondary Design Country]                varchar(max),
[VP: Secondary Design Region]                 varchar(max),
[Airbag Position]                             varchar(max),
[Airbag Module Supplier Group]                varchar(max),
[Airbag Module Supplier]                      varchar(max),
[Airbag Module Supplier Country]              varchar(max),
[Airbag Module Supplier Region]               varchar(max),
[Airbag Module Supplier Plant]                varchar(max),
[Airbag Module Units]                         varchar(max),
[Vehicle Units]                               varchar(max),
[Component Volume 2016]                       varchar(max),
[Component Volume 2017]                       varchar(max),
[Component Volume 2018]                       varchar(max),
[Component Volume 2019]                       varchar(max),
[Component Volume 2020]                       varchar(max),
[Component Volume 2021]                       varchar(max),
[Component Volume 2022]                       varchar(max),
[Component Volume 2023]                       varchar(max),
[Vehicle Volume 2016]                         varchar(max),
[Vehicle Volume 2017]                         varchar(max),
[Vehicle Volume 2018]                         varchar(max),
[Vehicle Volume 2019]                         varchar(max),
[Vehicle Volume 2020]                         varchar(max),
[Vehicle Volume 2021]                         varchar(max),
[Vehicle Volume 2022]                         varchar(max),
[Vehicle Volume 2023]                         varchar(max)
)